In [2]:
import pandas as pd

conda install pandas

In [12]:
print("Introduction to pandas")

Introduction to pandas

In [11]:
s = pd.Series([1,2,3,4,5] , index = ['a','b','c','d','e'])
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [13]:
df = pd.DataFrame({'name':['kunal','kakshi','naruto',]})

In [14]:
df

     name
0   kunal
1  kakshi
2  naruto

In [19]:
df = pd.read_csv("amazon_fires.csv", encoding="latin1")

In [21]:
df.head()

    ano      mes estado   numero  encontro
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999
2  2000  Janeiro   Acre  0 Fires  1/1/2000
3  2001  Janeiro   Acre  0 Fires  1/1/2001
4  2002  Janeiro   Acre  0 Fires  1/1/2002